[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=./lib/ds-test/src/',
'ac/=./lib/art-contracts/src/',
'sm/=./lib/solmate/src/',
'oz/=./lib/openzeppelin-contracts/contracts/',
'std/=./lib/forge-std/src/']

# See more config options https://github.com/gakonst/foundry/tree/master/config